#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use FindBin '$Bin';
use lib "$Bin/lib";

use WebScraper::Hargreaves::Lansdown;

my $hl = WebScraper::Hargreaves::Lansdown->new(
  $ENV{HL_USERNAME}, $ENV{HL_DOB},
  $ENV{HL_PASSWORD}, $ENV{HL_CODE},
);

$hl->overview;

