#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use FindBin '$Bin';
use lib "$Bin/lib";

use WebScraper::Hargreaves::Lansdown;

my $hl = WebScraper::Hargreaves::Lansdown->new({
  username => $ENV{HL_USERNAME},
  dob      =>$ENV{HL_DOB},
  password => $ENV{HL_PASSWORD},
  code     => $ENV{HL_CODE},
});

$hl->overview;

